### ISSUE TITLE
Can we update the background Image dynamically ?

### ISSUE THREAD

**Issue by ben55j** [sudar-life/flutter_slide_drawer#2]
Hello, 

Thank you for this great package ! I am trying to update the image dynamically when I press a button. 
The _set state_ have not effect on the image ... :( 

Any idea how I could achieve this ?

Thank you,
Benjamin

**Comment by sudar-life** [comment]
> Hello,
> 
> Thank you for this great package ! I am trying to update the image dynamically when I press a button. The _set state_ have not effect on the image ... :(
> 
> Any idea how I could achieve this ?
> 
> Thank you, Benjamin

I'm sorry for any inconvenience.

original version[1.0.0] couldn't change drawer background image

so I had released new update version including function of your request

check new version and have a check that image can change.

thank you :)
