### ISSUE TITLE
How to support RTL ( RightToLeft) open 

### ISSUE THREAD

**Issue by eslambesooo** [sudar-life/flutter_slide_drawer#3]
How to support opening slider from the right for RTL Languages.

Thanks

**Comment by sudar-life** [comment]
@eslambesooo Thank you using my lib. I've work done now. 
you can use updated version(1.0.2), then you can handle direction option.
have a check README document.

**Comment by eslambesooo** [comment]
Thanks to you , i was about to pull request for my updates for it , but now will update the version.

Thanks again
